name: stock_investment_app
description: A Flutter application for stock investment.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  mobx:
    git:
      url: https://github.com/altynbek132/mobx.dart
      path: mobx

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shimmer: ^3.0.0

  utils:
    git:
      url: https://github.com/altynbek132/flutter_util_packages
      path: packages/utils
  # ! overridden
  mobx: any
  flutter_mobx:
    git:
      url: https://github.com/altynbek132/mobx.dart
      path: flutter_mobx
  elementary:
    git:
      url: https://github.com/altynbek132/flutter-elementary
      path: packages/elementary
  disposing:
    git:
      url: https://github.com/altynbek132/dart_disposing
      path: packages/disposing
  awesome_extensions:
    git:
      url: https://github.com/altynbek132/awesome_extensions

  logger: ^2.6.0
  flutter_screenutil: 5.9.1
  provider: ^6.1.5
  collection: ^1.19.1
  reactive_forms: ^18.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  sliver_tools: ^0.2.12
  permission_handler: ^12.0.1
  meta: ^1.16.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  device_preview: ^1.3.1

  expandable: ^5.0.1
  dio: ^5.8.0+1
  mask_text_input_formatter: ^2.9.0
  infinite_scroll_pagination: ^4.1.0
  sliding_up_panel: ^2.0.0+1
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.2.0
  render_metrics: ^2.0.2
  uuid: ^4.5.1
  platform_info: ^5.0.0
  ensure_visible_when_focused: ^1.2.0
  smooth_page_indicator: ^1.2.1
  modal_bottom_sheet: ^3.0.0
  pretty_dio_logger: ^1.4.0
  url_launcher: ^6.3.1
  percent_indicator: ^4.2.5
  yx_scope: ^1.0.2
  yx_scope_flutter: ^1.0.2
  intl: ^0.20.2
  synchronized: ^3.4.0
  auto_size_text: ^3.0.0
  animated_size_and_fade: ^5.1.1
  boxy: ^2.2.1
  bottom_sheet: ^4.0.4
  pinput: ^5.0.1

  # firebase_core: ^3.15.1
  # firebase_auth: ^5.6.2
  # firebase_crashlytics: ^4.3.9
  dropdown_button2: ^2.3.9
  widget_mask: ^1.0.0+0
  svg_clip: ^0.0.2
  rx_shared_preferences: ^3.1.0
  fresh_dio: ^0.4.3
  dio_curl_interceptor: ^3.2.6
  octopus:
    git:
      url: https://github.com/altynbek132/octopus
  l: ^5.0.1
  retrofit: ^4.7.2
  story_view:
    git:
      url: https://github.com/altynbek132/story_view
  audioplayers: ^6.5.0
  youtube_player_flutter: ^9.1.2
  pdfx: ^2.9.2
  share_plus: ^11.1.0
  in_app_review: ^2.0.10
  image_picker: ^1.2.0
  image: ^4.5.4
  webview_flutter: ^4.13.0
  custom_refresh_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf
        - asset: assets/fonts/SFProText-BoldItalic.ttf
        - asset: assets/fonts/SFProText-Heavy.ttf
        - asset: assets/fonts/SFProText-HeavyItalic.ttf
        - asset: assets/fonts/SFProText-Medium.ttf
        - asset: assets/fonts/SFProText-MediumItalic.ttf
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-Semibold.ttf
        - asset: assets/fonts/SFProText-SemiboldItalic.ttf
