name: api
description: "A new Flutter package project."
version: 0.0.1
homepage:
# resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^8.1.0
  collection: ^1.19.1
  http: ^1.4.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # swagger_dart_code_generator: ^3.0.3
  # chopper_generator: ^8.1.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0
  freezed: ^3.0.6

flutter:
